api/server.js, controllers/users-router.js, models/User-Model.js
We added two endpoints
- GET: '/' => returns a welcome
- GET: '/users' => returns a list of users
- Used Postman to retrieve the list of users
- [x ] I have performed a self-review of my own code
=> added an endpoint to retrieve the users

yarn.lock
Fixed the yarn.lock issue. re-ran yarn
- remove node_modules and yarn.lock and re-installed all packages by running yarn
- remove node_modules and yarn.lock and re-installed all packages by running yarn
=> fixed yarn.lock issue

package.json
The start script in package.json was 'Start'. Changed to lowercase 'start'
- ran the yarn start script and everything works as it should
=> changed the start script to all-lowercase in package.json

controllers/auth-router.js
Setting up the auth router for registration and login.
=> Auth Router Work in Progress

api/server.js, config/passport-setup.js
since it's located .gitignore and not being accessible to the app. We just reference the env variables by using process.env.ENV instead of process.env.ENV || keys.env-variable
=> removed references to the config/keys.js file

api/server.js, config/passport-setup.js, controllers/auth-router.js, controllers/authCheck.js
the heroku application keeps throwing an error saying: cannot find the module './config/keys.js'.
In the last PR we removed references to this file and it still threw the same error. 
This time, we removed all imports of that file altogether
=> removed all the import of config/keys

config/passport-setup.js, controllers/auth-router.js, controllers/users-router.js, models/User-Model.js
The naming of the user model file was inconsistent with linux naming conventions. Changed the file name to all lowercase.
=> changed the import name of the user model file

api/server.js, controllers/auth-router.js
Fixed cors issues for frontend to fetch data
=> 🐛 Fixing cors issue

controllers/auth-router.js
=> 🐛 Redirect url fixed

database/migrations/20190606182127_UsersWorkflows.js
UserWorkflows migration file fix
=> 🐛 Production DB Fix

database/migrations/20190606182938_Users.js
=> Fix for users

database/seeds/001-Users.js
User ID seeder fix uuid to int
=> 🐛 user id seeder fix

database/seeds/001-Users.js
=> 🐛 min max changed to 1:10

database/migrations/20190606182938_Users.js
change fb / google id from int to bigint
=> 🐛 google/fb id from int to bigint

controllers/auth-router.js
Fix issue where user is auto logged in using already stored google account
=> 🐛 Fix issue making users auto-login

controllers/workflows-router.js, database/migrations/20190606183127_Workflows.js, models/workflow-models.js
Must be logged in for each endpoint
=> 🐛 GET /workflows & POST /workflows now working

api/server.js, api/serverConfig.js, controllers/workflows-router.js
Fixes cors issues by changing config entirely. 
Cors config object is now passed into `cors` node package
=> 🐛 New cors config to prevent preflight errors

config/passport-setup.js
changed callback URL on facebookStrategy and changed configs for facebook
=> 🐛 It works!!!

knexfile.js
Changed the local db to use postgres instead of sqlite3 for consistency
=> changed the local db to use Postgres

controllers/profile-router.js
Fixes bug where /profile only return user info from google auth cookie and not correct info from database
=> 🐛 GET /profile correct info

.eslintrc, config/passport-setup.js, database/migrations/20190606182938_Users.js
Profile image from google or facebook is added to users table under 'pic' column on signup
=> ✨ Users now have a profile pic!

api/server.js, controllers/ussd-router.js, package.json, yarn.lock
Adds the ussd-menu-builder npm package to build states for our flows.
This gets a basic example flow working.
=> :sparkles: integrate ussd route

api/serverConfig.js, controllers/answers-router.js, controllers/auth-router.js, controllers/clients-router.js, controllers/profile-router.js, controllers/questions-router.js, controllers/users-router.js, controllers/userworkflows-router.js, controllers/workflows-router.js, database/migrations/20190606182958_Clients.js, database/migrations/20190606183127_Workflows.js, database/seeds/006-Clients.js, database/seeds/007-Answers.js, database/seeds/008-Questions.js, database/seeds/009-Workflows.js, database/seeds/010-UsersWorkFlows.js, knexfile.js, models/answer-models.js, models/client-models.js, models/question-models.js, models/user-workflow-models.js, models/workflow-models.js
=> linting fix

controllers/workflows-router.js
Fix GET /workflow/{id} endpoint
=> 🐛 Fix GET /workflow

database/migrations/20190606183050_Questions.js, database/migrations/20190614142959_session-table.js
also created a sessions table to log the sessions
=> :art: changed the questions table to remove the options field

controllers/ussd-router.js, models/ussd-model.js
added ussd-model to record the sessions
=> :sparkles: added ussd-model

controllers/ussd-router.js, database/seeds/008-Questions.js, models/ussd-model.js
Fixed the errors on the ussd-route
Fixed the questions seed file.
Fixed the ussd model file as well
=> fixed the ussd-route

TEAM_DEVELOPMENT_BRANCH.md, controllers/profile-router.js, controllers/ussd-router.js, models/profile-model.js
User can finally delete their own User - Profile
- [x New feature (non-breaking change which adds functionality)
Tested with Postman
=> Feature: Delete User Profile

database/migrations/20190617122737_client-response.js
Added the Client Response table that will be referencing Questions and Answers so that way the client can send it's response when prompted by Questions.
Will be going back and forth between questions and answers table. 
-[ x] My code follows the style guidelines of this project
=> Database: Client Response Table

controllers/auth-router.js
changed /profile to /workflows in server redirect and APIs
Changed redirect route to /workflows and updated auth config with Facebook and Google
=> 🎉 Changing redirect on BE + Google and Fabeook APIs

api/server.js, config/passport-setup.js
Fix crash after first time login with google
=> Fix google register

controllers/responses.js, database/migrations/003-Workflows.js, models/responses.js
GET: `/responses/{workflow}?tree=true` returns responses in a tree array
=> Responses endpoint updates

README.md, africas-talking.sample.js
Sample of how the Africas Talking file would be set up so that way you can test out what is built on the USSD router by using the Simulator on Africas Talking.
- [x New feature (non-breaking change which adds functionality)
=> Africas Talking Sample File Setup

README.md
=> Mostly updated ReadMe

controllers/ussd-router.js, database/migrations/007-Sessions.js, models/ussd-model.js
=> ✨ Show current response when displaying options
